name: Script_test
# This workflow is  triggered on pushes, pull requests to the repository.
on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
 install-windows-powershell:
    name: install-windows-powershell
    runs-on: windows-latest
    steps:
      - name: test_install_on_windows_powershell
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "pull_request") {
            $script_source = $env:GITHUB_HEAD_REF.replace('refs/heads/', '')
          } else {
            $script_source = $env:GITHUB_REF.replace('refs/heads/', '')
          }
          . { iwr -useb https://raw.githubusercontent.com/nxxm/nxxm/$script_source/install/install_for_windows.ps1 } | iex 
          if ($?) {}
          else {exit 1}

          # Test install succeeeded 
          if (!(Test-Path "C:\\ProgramData\\nxxm\\nxxm.exe" -PathType leaf)) { exit 1; }
          if (!(Test-Path "C:\\.nxxm\\7803ad7\\downloads\\nodejs.zip" -PathType leaf)) { exit 1; }
        shell: powershell 
